-- ============================================
-- CYNOX BLOG - POSTGRESQL DATABASE STRUCTURE
-- Migrated from Oracle
-- ============================================

CREATE TABLE IF NOT EXISTS admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    content TEXT,
    image VARCHAR(500),
    author VARCHAR(100),
    category VARCHAR(100),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    seo_title VARCHAR(255),
    meta_description VARCHAR(500),
    seo_keywords VARCHAR(500),
    focus_keyword VARCHAR(255),
    url_slug VARCHAR(255),
    canonical_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS admin_password_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    otp VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used INTEGER,
    created_at TIMESTAMP(6),

    CONSTRAINT fk_reset_admin
        FOREIGN KEY (admin_id)
        REFERENCES admin_users(id)
);

-- ============================================
-- VERIFY TABLES
-- ============================================

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'admin',
      'admin_users',
      'blogs',
      'admin_password_resets'
  )
ORDER BY table_name;